; This file can be edited to change the style of the application
; See Styling Qt Quick Controls 2 in the documentation for details:
; http://doc.qt.io/qt-5/qtquickcontrols2-styles.html

[Controls]
Style=Material


[Material]
Theme=Dark
Primary=#42b649
Accent=#42b649
Foreground=#f0e6d2
Background=#12100d

